### ISSUE TITLE
Update email texts

### ISSUE THREAD

**Issue by banton** [pvarki/python-pvas-takbackend#16]
# Kirjautuminen

## Kirjaudu PVArki-tilauspalveluun

Tervetuloa käyttämään PVArki-tilauspalvelua!

Sähköpostillasi on pyydetty kirjautumaan PVArki-palveluun. Mikäli tämä on tarkoitus, voit kirjautua tilauspalveluun tästä linkistä:

[linkkiURI]

Mikäli et ole halunnut kirjautua, voit poistaa tämän viestin.

Terveisin,

PVArki-tiimi

# Tilausvahvistus

## Tilausvahvistus PVArki-palveluista

Hei!

PVArki-tilaus vastaanotettu. Käynnistämme palvelut tilattuna aikana tai välittömästi, mikäli valittu aikaikkuna oli "heti". 

Palveluiden pystyttämisessä kestää yleensä muutamia minuutteja, ja toimitamme palveluiden käynnistyttyä uuden sähköpostin jonka avulla pääset käyttämään tai jakamaan palvelua käyttäjille.

Paketti toimitetaan yksilöllisen linkin muodossa Tilauspalveluun, jonka avulla jokainen käyttäjä saa kaikki tarpeelliset tiedot palveluiden käyttöönottoon, käyttöohjeet ja linkit mahdollisiin muihin latauksiin. Palvelusta löytyy myös mahdollisuus ladata tiedostot omalle laitteelle vapaalla tavalla jaeltavaksi, tai paikan päällä näppärästi käytettäväksi QR-koodiksi.

Mikäli haluat tehdä muutoksia tilaukseesi, voit tehdä sen kirjautumalla takaisin PVArki-tilauspalveluun osoitteessa https://tilaa.pvarki.fi ja muokata siellä harjoitusta, tai luoda uusi.

Kiitos, että käytät arjen välineitä ja PVArki-palvelua!

Terveisin,

PVArki-tiimi

# Palveluiden toimittaminen

## Tässä PVArki-tilauksesi

Hei!

Olet aiemmin tilannut PVArki-palveluita, tilauksesi on nyt valmis ja käytettävissä.

Pääset käyttämään tilaustasi kirjautumalla PVArki-tilauspalveluun ja valitsemalla kyseinen tilaus, johon palvelut on tilattu. Käynnissä olevat palvelut näkyvät helposti ensimmäisenä palvelussa.

Voit myös mennä suoraan tilaukseesi tästä linkistä: [DEEPlinkkiURI] 

Kiitos, että käytät arjen välineitä ja PVArki-palvelua!

Terveisin,

PVArki-tiimi

# Palvelujakso päättynyt

## PVArki-tilaus on päättynyt ja sammutettu

Hei!

Aiemmin tilaamasi PVArki-palvelutilaus on ajastetun mukaisesti loppunut, ja kaikki palvelut ovat sammutettu. Operaatiotiedot ovat tuhottu tietoturvallisesti.

Tilaushistoria ja mahdolliset kustannuspaikkatiedot ovat tallennettu ja saatavilla jatkossakin.

Mikäli haluat tilata lisää PVArki-palveluita, se tapahtuu helposti osoitteessa https://tilaa.pvarki.fi

Kiitos, että käytät arjen välineitä ja PVArki-palvelua!

Terveisin,

PVArki-tiimi

**Comment by rambo** [comment]
Fixed by https://github.com/pvarki/python-pvas-takbackend/pull/17 (in the parts that this component can affect)
