### ISSUE TITLE
TAK fighter landing page: add quick instructions before anything

### ISSUE THREAD

**Issue by rambo** [pvarki/python-pvas-takbackend#22]
### User story
Taistelijana, joka ottaa TAKin käyttöön, haluan, että

näen heti taistelijan ländärillä edessä toimintaohjeet, jotta ymmärrän, miksi tulin tälle sivulle, mitä täällä teen ja miten. 
Viisi bullettia alta Mikolta

![Image](https://user-images.githubusercontent.com/53127823/223181160-35826505-9a7b-4412-b323-dddf33d662d2.jpeg)

**Comment by M1kk0H** [comment]
This has been implemented 11/23
