### ISSUE TITLE
TAK leader landing page: add instructions before anything

### ISSUE THREAD

**Issue by rambo** [pvarki/python-pvas-takbackend#23]
TAKin joukolleni käyttöön ottavana johtajana haluan, että

kun vastaanotan tilauslinkkini ja saan käteeni johtajan landing-sivun, missä on QR-koodi ja linkki perusteiden jakoon joukolleni,

saan heti kuvan, 1) **miksi sain tämän sivun**, 2) **miten suunnittelen ja toimeenpanen TAKin **käytön** joukollani (eli mitä arvoa tällä tuotteella saan)**, 3) **miten toteutan perusteiden jaon joukolleni (näytän qr-koodia ja ohjeistan taistelijat)**

Ohessa kuva toivotusta setupista sivulla, huom, "Tähän filu toistaiseksi" -> markdown "Käyttö komppaniassa" alla

![Image](https://user-images.githubusercontent.com/53127823/223183655-160c2d2d-bf3e-4b19-bef2-2d38c6a6098b.jpg)

### 2. Mihin käytän joukossani, ja miten käsken sen?
Tähän filu, ALLA MARKDOWN ...

# Käyttö komppaniassa: TAK

## Tilannekuvatuote TAK
TAKia käytetään
- 1. Omien sijainnin seuraamiseen.
- 2. Tiedusteluhavaintojen lähettämiseen komentopaikalle
- 3. Tiedustelutilannekuvan vastaanottoon komentopaikalta.

## 1. Omien sijainnin seuranta
TAKissa käytetään ryhmäkohtaisia peitteitä ja joukkuekohtaisia peitevärejä.

### Joukkueet
Viestikäskyssä käsketään
- Joukkueen peitenimi ja peiteväri, esim. **1J: APINA, sininen**

### Ryhmät
**Ryhmät** käyttävät joukkueensa peiteväriä, ja keksivät oman peitenimensä, esimerkiksi **1R/1J MUNKKI, sininen**

### Partiot
**Partiot** käyttävät joukkueensä peiteväriä ja ryhmänsä peitenimeä, esim. 2P **MUNKKI2, sininen**

Ryhmät ilmoittavat peitteensä joukkueenjohtajalleen ja komentopaikalle.

## 2. Tiedusteluhavaintojen lähittäminen
Tiedusteluhavainnot lähetetään merkkeinä **komentopaikan** tunnukselle. Toistaiseksi merkit eivät päivity vastaanottajilla automaattisesti, jos siirrät tai poistat merkkiä omalla laitteellasi. Poista merkki itseltäsi, kun et enää tarvitse sitä.

## 3. Tilannekuvan vastaanotto
Komentopaikka lähettää kerran vuorokaudessa tai tilanteen muuttuessa data packagen eli karttakelmun nimellä "päivämäärä_juoksevaluku" kaikille käyttäjille. Package sisältää tiedustelutilanteen ja/tai halutun tilannekuvan.

**Comment by benjamsf** [comment]
Done at RMUI v1.0
